#!/bin/sh
echo "preinst"
#打包的时候替换
PAK_ARCH="amd64"
#错误输出位置
ERR_OUT=/tmp/EasyConnect.install.error

#清空之前可能存在的错误日志信息
if [ -f $ERR_OUT ]
then
	echo > $ERR_OUT
fi
uname -a |grep x86_64
if [ $? -eq 0 ]
then
	if [ $PAK_ARCH = "i386" ]
	then
		echo "deb pkg is 32bit, os is 64bit, can't install..."
		echo "deb pkg is 32bit, os is 64bit, can't install..." >>$ERR_OUT
		exit -1
	fi
else
	if [ $PAK_ARCH = "amd64" ]
	then
		echo "deb pkg is 64bit, os is 32bit, can't install..."
		echo "deb pkg is 64bit, os is 32bit, can't install..." >>$ERR_OUT
		exit -1
	fi
fi
####################
#系统判断
####################
detect_distro ()
{
    RELEASE_ID=`lsb_release -i | cut -f2`
    VERSION_ID=`lsb_release -r | cut -f2`

    case $RELEASE_ID in
        ubuntu|Ubuntu|UBUNTU)
            RELEASE_TYPE=ubuntu
            ;;
        *)
            RELEASE_TYPE=unkown
            ;;
        *)
    esac

}
###################
#删除系统服务
###################
#传统启动方式
init_del_service()
{
    service EasyMonitor.sh stop 
    update-rc.d -f EasyMonitor.sh remove
    \rm  /etc/init.d/EasyMonitor.sh
}
#ubuntu15.04 之下版本系统服务处理函数
upstart_del_service()
{
    stop EasyMonitor   >  /dev/null 2>&1
    \rm  /etc/init/EasyMonitor.conf   >  /dev/null 2>&1
}
#ubuntu15.04及之上  版本系统服务处理函数
system_del_service()
{
    systemctl stop EasyMonitor   >  /dev/null 2>&1
    systemctl disable EasyMonitor   >  /dev/null 2>&1
}

del_service()
{

    if [ $RELEASE_TYPE = "ubuntu" ]	
    then
        #低于ubuntu15.04
        VERSION_YEA=`echo $VERSION_ID|awk -F "." '{print$1}'`	
        if [ ${VERSION_YEA} -lt "15" ]
        then
            upstart_del_service
        else
            system_del_service
        fi
    else
        system_del_service
    fi

}

#杀死可能存在的EC进程
kill_programe()
{

    #停止所有相关进程
    pidof EasyMonitor
    if [ $? -eq 0 ];then
        killall  EasyMonitor
    fi
    pidof EasyMonitor
    if [ $? -eq 0 ];then
        killall  -9 EasyMonitor
    fi

    pidof ECAgent
    if [ $? -eq 0 ];then
        killall ECAgent
    fi
    pidof ECAgent
    if [ $? -eq 0 ];then
        killall -9 ECAgent
    fi

    pidof EasyConnect
    if [ $? -eq 0 ];then
        killall EasyConnect
    fi
    pidof EasyConnect
    if [ $? -eq 0 ];then
        killall -9 EasyConnect
    fi

    pidof CSClient
    if [ $? -eq 0 ];then
        killall CSClient
    fi
    pidof CSClient
    if [ $? -eq 0 ];then
        killall -9 CSClient
    fi

    pidof svpnservice
    if [ $? -eq 0 ];then
        killall svpnservice 
    fi
    pidof svpnservice
    if [ $? -eq 0 ];then
        killall -9 svpnservice
    fi


}

#停止服务
detect_distro
del_service
#杀死相关进程
kill_programe

exit 0
